### ISSUE TITLE
Need a CLI for DELi

### ISSUE THREAD

**Issue by jimmyjbling** [Popov-Lab-UNC/DELi#6]
Calling a DEL selection isn't really a package, its more of a tool so we should have this be callable via CLI (at least the calling commands)

**Comment by Brandon-Cole** [comment]
quick question here, I know python3 deli_run.py -h is already available for users. Is CLI use case so that users could submit via a prompt for each arg? let me know what you think!

**Comment by jimmyjbling** [comment]
I'm think of using click for this cause it will let us use the command groups
